print("Hello world")
print("Hey Adarsh Choubey")
print("Python is a high level language !!")
print("Python is a language")
print("My Name Is Aadarsh")
print("Restaurant_Analysis")
print("Analysis_report")